//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SitecoreConverter.Core.Umbraco6DocumentService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="documentServiceSoap", Namespace="http://umbraco.org/webservices/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(documentProperty[]))]
    public partial class documentService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback createOperationCompleted;
        
        private System.Threading.SendOrPostCallback readOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadPublishedOperationCompleted;
        
        private System.Threading.SendOrPostCallback readListOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback WebservicesEnabledOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserAuthenticatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserHasAccessOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public documentService() {
            this.Url = global::SitecoreConverter.Core.Properties.Settings.Default.Core_Umbraco6DocumentService_documentService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event createCompletedEventHandler createCompleted;
        
        /// <remarks/>
        public event readCompletedEventHandler readCompleted;
        
        /// <remarks/>
        public event ReadPublishedCompletedEventHandler ReadPublishedCompleted;
        
        /// <remarks/>
        public event readListCompletedEventHandler readListCompleted;
        
        /// <remarks/>
        public event updateCompletedEventHandler updateCompleted;
        
        /// <remarks/>
        public event deleteCompletedEventHandler deleteCompleted;
        
        /// <remarks/>
        public event WebservicesEnabledCompletedEventHandler WebservicesEnabledCompleted;
        
        /// <remarks/>
        public event UserAuthenticatesCompletedEventHandler UserAuthenticatesCompleted;
        
        /// <remarks/>
        public event UserHasAccessCompletedEventHandler UserHasAccessCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://umbraco.org/webservices/create", RequestNamespace="http://umbraco.org/webservices/", ResponseNamespace="http://umbraco.org/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int create(documentCarrier carrier, string username, string password) {
            object[] results = this.Invoke("create", new object[] {
                        carrier,
                        username,
                        password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void createAsync(documentCarrier carrier, string username, string password) {
            this.createAsync(carrier, username, password, null);
        }
        
        /// <remarks/>
        public void createAsync(documentCarrier carrier, string username, string password, object userState) {
            if ((this.createOperationCompleted == null)) {
                this.createOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateOperationCompleted);
            }
            this.InvokeAsync("create", new object[] {
                        carrier,
                        username,
                        password}, this.createOperationCompleted, userState);
        }
        
        private void OncreateOperationCompleted(object arg) {
            if ((this.createCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createCompleted(this, new createCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://umbraco.org/webservices/read", RequestNamespace="http://umbraco.org/webservices/", ResponseNamespace="http://umbraco.org/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public documentCarrier read(int id, string username, string password) {
            object[] results = this.Invoke("read", new object[] {
                        id,
                        username,
                        password});
            return ((documentCarrier)(results[0]));
        }
        
        /// <remarks/>
        public void readAsync(int id, string username, string password) {
            this.readAsync(id, username, password, null);
        }
        
        /// <remarks/>
        public void readAsync(int id, string username, string password, object userState) {
            if ((this.readOperationCompleted == null)) {
                this.readOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreadOperationCompleted);
            }
            this.InvokeAsync("read", new object[] {
                        id,
                        username,
                        password}, this.readOperationCompleted, userState);
        }
        
        private void OnreadOperationCompleted(object arg) {
            if ((this.readCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.readCompleted(this, new readCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://umbraco.org/webservices/ReadPublished", RequestNamespace="http://umbraco.org/webservices/", ResponseNamespace="http://umbraco.org/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public documentCarrier ReadPublished(int id, string username, string password) {
            object[] results = this.Invoke("ReadPublished", new object[] {
                        id,
                        username,
                        password});
            return ((documentCarrier)(results[0]));
        }
        
        /// <remarks/>
        public void ReadPublishedAsync(int id, string username, string password) {
            this.ReadPublishedAsync(id, username, password, null);
        }
        
        /// <remarks/>
        public void ReadPublishedAsync(int id, string username, string password, object userState) {
            if ((this.ReadPublishedOperationCompleted == null)) {
                this.ReadPublishedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadPublishedOperationCompleted);
            }
            this.InvokeAsync("ReadPublished", new object[] {
                        id,
                        username,
                        password}, this.ReadPublishedOperationCompleted, userState);
        }
        
        private void OnReadPublishedOperationCompleted(object arg) {
            if ((this.ReadPublishedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadPublishedCompleted(this, new ReadPublishedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://umbraco.org/webservices/readList", RequestNamespace="http://umbraco.org/webservices/", ResponseNamespace="http://umbraco.org/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public documentCarrier[] readList(int parentid, string username, string password) {
            object[] results = this.Invoke("readList", new object[] {
                        parentid,
                        username,
                        password});
            return ((documentCarrier[])(results[0]));
        }
        
        /// <remarks/>
        public void readListAsync(int parentid, string username, string password) {
            this.readListAsync(parentid, username, password, null);
        }
        
        /// <remarks/>
        public void readListAsync(int parentid, string username, string password, object userState) {
            if ((this.readListOperationCompleted == null)) {
                this.readListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreadListOperationCompleted);
            }
            this.InvokeAsync("readList", new object[] {
                        parentid,
                        username,
                        password}, this.readListOperationCompleted, userState);
        }
        
        private void OnreadListOperationCompleted(object arg) {
            if ((this.readListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.readListCompleted(this, new readListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://umbraco.org/webservices/update", RequestNamespace="http://umbraco.org/webservices/", ResponseNamespace="http://umbraco.org/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void update(documentCarrier carrier, string username, string password) {
            this.Invoke("update", new object[] {
                        carrier,
                        username,
                        password});
        }
        
        /// <remarks/>
        public void updateAsync(documentCarrier carrier, string username, string password) {
            this.updateAsync(carrier, username, password, null);
        }
        
        /// <remarks/>
        public void updateAsync(documentCarrier carrier, string username, string password, object userState) {
            if ((this.updateOperationCompleted == null)) {
                this.updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateOperationCompleted);
            }
            this.InvokeAsync("update", new object[] {
                        carrier,
                        username,
                        password}, this.updateOperationCompleted, userState);
        }
        
        private void OnupdateOperationCompleted(object arg) {
            if ((this.updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://umbraco.org/webservices/delete", RequestNamespace="http://umbraco.org/webservices/", ResponseNamespace="http://umbraco.org/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void delete(int id, string username, string password) {
            this.Invoke("delete", new object[] {
                        id,
                        username,
                        password});
        }
        
        /// <remarks/>
        public void deleteAsync(int id, string username, string password) {
            this.deleteAsync(id, username, password, null);
        }
        
        /// <remarks/>
        public void deleteAsync(int id, string username, string password, object userState) {
            if ((this.deleteOperationCompleted == null)) {
                this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
            }
            this.InvokeAsync("delete", new object[] {
                        id,
                        username,
                        password}, this.deleteOperationCompleted, userState);
        }
        
        private void OndeleteOperationCompleted(object arg) {
            if ((this.deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://umbraco.org/webservices/WebservicesEnabled", RequestNamespace="http://umbraco.org/webservices/", ResponseNamespace="http://umbraco.org/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WebservicesEnabled() {
            object[] results = this.Invoke("WebservicesEnabled", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WebservicesEnabledAsync() {
            this.WebservicesEnabledAsync(null);
        }
        
        /// <remarks/>
        public void WebservicesEnabledAsync(object userState) {
            if ((this.WebservicesEnabledOperationCompleted == null)) {
                this.WebservicesEnabledOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWebservicesEnabledOperationCompleted);
            }
            this.InvokeAsync("WebservicesEnabled", new object[0], this.WebservicesEnabledOperationCompleted, userState);
        }
        
        private void OnWebservicesEnabledOperationCompleted(object arg) {
            if ((this.WebservicesEnabledCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WebservicesEnabledCompleted(this, new WebservicesEnabledCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://umbraco.org/webservices/UserAuthenticates", RequestNamespace="http://umbraco.org/webservices/", ResponseNamespace="http://umbraco.org/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UserAuthenticates(string username, string password) {
            object[] results = this.Invoke("UserAuthenticates", new object[] {
                        username,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UserAuthenticatesAsync(string username, string password) {
            this.UserAuthenticatesAsync(username, password, null);
        }
        
        /// <remarks/>
        public void UserAuthenticatesAsync(string username, string password, object userState) {
            if ((this.UserAuthenticatesOperationCompleted == null)) {
                this.UserAuthenticatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserAuthenticatesOperationCompleted);
            }
            this.InvokeAsync("UserAuthenticates", new object[] {
                        username,
                        password}, this.UserAuthenticatesOperationCompleted, userState);
        }
        
        private void OnUserAuthenticatesOperationCompleted(object arg) {
            if ((this.UserAuthenticatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserAuthenticatesCompleted(this, new UserAuthenticatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://umbraco.org/webservices/UserHasAccess", RequestNamespace="http://umbraco.org/webservices/", ResponseNamespace="http://umbraco.org/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UserHasAccess(string username) {
            object[] results = this.Invoke("UserHasAccess", new object[] {
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UserHasAccessAsync(string username) {
            this.UserHasAccessAsync(username, null);
        }
        
        /// <remarks/>
        public void UserHasAccessAsync(string username, object userState) {
            if ((this.UserHasAccessOperationCompleted == null)) {
                this.UserHasAccessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserHasAccessOperationCompleted);
            }
            this.InvokeAsync("UserHasAccess", new object[] {
                        username}, this.UserHasAccessOperationCompleted, userState);
        }
        
        private void OnUserHasAccessOperationCompleted(object arg) {
            if ((this.UserHasAccessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserHasAccessCompleted(this, new UserHasAccessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://umbraco.org/webservices/")]
    public partial class documentCarrier {
        
        private int idField;
        
        private string nameField;
        
        private documentProperty[] documentPropertiesField;
        
        private int documentTypeIDField;
        
        private int parentIDField;
        
        private bool hasChildrenField;
        
        private EPublishAction publishActionField;
        
        private bool publishedField;
        
        private System.DateTime releaseDateField;
        
        private System.DateTime expireDateField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public documentProperty[] DocumentProperties {
            get {
                return this.documentPropertiesField;
            }
            set {
                this.documentPropertiesField = value;
            }
        }
        
        /// <remarks/>
        public int DocumentTypeID {
            get {
                return this.documentTypeIDField;
            }
            set {
                this.documentTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public int ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
            }
        }
        
        /// <remarks/>
        public bool HasChildren {
            get {
                return this.hasChildrenField;
            }
            set {
                this.hasChildrenField = value;
            }
        }
        
        /// <remarks/>
        public EPublishAction PublishAction {
            get {
                return this.publishActionField;
            }
            set {
                this.publishActionField = value;
            }
        }
        
        /// <remarks/>
        public bool Published {
            get {
                return this.publishedField;
            }
            set {
                this.publishedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReleaseDate {
            get {
                return this.releaseDateField;
            }
            set {
                this.releaseDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpireDate {
            get {
                return this.expireDateField;
            }
            set {
                this.expireDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://umbraco.org/webservices/")]
    public partial class documentProperty {
        
        private object propertyValueField;
        
        private string keyField;
        
        /// <remarks/>
        public object PropertyValue {
            get {
                return this.propertyValueField;
            }
            set {
                this.propertyValueField = value;
            }
        }
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://umbraco.org/webservices/")]
    public enum EPublishAction {
        
        /// <remarks/>
        Ignore,
        
        /// <remarks/>
        Publish,
        
        /// <remarks/>
        Unpublish,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void createCompletedEventHandler(object sender, createCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void readCompletedEventHandler(object sender, readCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class readCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal readCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public documentCarrier Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((documentCarrier)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ReadPublishedCompletedEventHandler(object sender, ReadPublishedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadPublishedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadPublishedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public documentCarrier Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((documentCarrier)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void readListCompletedEventHandler(object sender, readListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class readListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal readListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public documentCarrier[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((documentCarrier[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void updateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void deleteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void WebservicesEnabledCompletedEventHandler(object sender, WebservicesEnabledCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WebservicesEnabledCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WebservicesEnabledCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void UserAuthenticatesCompletedEventHandler(object sender, UserAuthenticatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserAuthenticatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserAuthenticatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void UserHasAccessCompletedEventHandler(object sender, UserHasAccessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserHasAccessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserHasAccessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591