//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitecoreConverter.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://udvikling.3fi.dk/sitecore/client/api/api.asmx")]
        public string Core_Sitecore43_Sitecore_x0020_Client_x0020_API {
            get {
                return ((string)(this["Core_Sitecore43_Sitecore_x0020_Client_x0020_API"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.3f-fagforening.dk/sitecore/shell/webservice/service.asmx")]
        public string Core_sitecore6_Visual_x0020_Sitecore_x0020_Service {
            get {
                return ((string)(this["Core_sitecore6_Visual_x0020_Sitecore_x0020_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://local3fsitecore/sitecore%20modules/Shell/ExtendedSitecoreAPI/Security.asmx" +
            "")]
        public string Core_sitecore6_Security {
            get {
                return ((string)(this["Core_sitecore6_Security"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://arkitema.web01.cabana.dk/sitecore/shell/webservice/service.asmx")]
        public string Core_Sitecore5x_Visual_x0020_Sitecore_x0020_Service {
            get {
                return ((string)(this["Core_Sitecore5x_Visual_x0020_Sitecore_x0020_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://internet.regioner.web01.cabana.dk/sitecore%20modules/shell/extendedsitecor" +
            "eapi5x/security.asmx")]
        public string Core_net_cohaesio_instant_sdu_webred531_Security {
            get {
                return ((string)(this["Core_net_cohaesio_instant_sdu_webred531_Security"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://umbraco.dtl.web01.cabana.dk/umbraco/webServices/api/DocumentService.asmx")]
        public string Core_Umbraco6DocumentService_documentService {
            get {
                return ((string)(this["Core_Umbraco6DocumentService_documentService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://umbraco.dtl.web01.cabana.dk/umbraco/webService.asmx")]
        public string Core_Umbraco6xWebService_webService {
            get {
                return ((string)(this["Core_Umbraco6xWebService_webService"]));
            }
        }
    }
}
